### ISSUE TITLE
Find & Replace isn't working

### ISSUE THREAD

**Issue by crustySenpai** [NX-Editor/NX-Editor#34]
So i'm not sure if i do anything wrong but if i try to use Find & Replace under Edit it opens up and i can find words/numbers but i can't replace any of the words/numbers also non of the buttons beside the bars seem to do anything

https://github.com/NX-Editor/NX-Editor/assets/83429736/f88f1f48-3cbe-4bd8-a537-09bdf4ccea7a

i'm completely new to totk modding and if i'm just dumb or this is a known issue i apologize

**Comment by ArchLeaders** [comment]
This is an issue with AvaloniaEdit I think, although I can't consistently re-create it. You can use `Enter` to find/replace the next found word though.

I also think AvaloniaEdit already fixed this issue, it's just not on the main builds yet.

https://github.com/AvaloniaUI/AvaloniaEdit/issues/336

---

I'll leave this issue open until I update to the next avalonia rc though.

**Comment by crustySenpai** [comment]
alright good to know and pressing enter didn't replace anything just skips to the next word so basically just the search function
but as you already said guess i'll just wait then for the next update thanks for your reply tough

**Comment by ArchLeaders** [comment]
Should be fixed in 0.3.6 if you want to test.

**Comment by crustySenpai** [comment]
still the same thing problem like before, i'm gonna test if this maybe is just a me issue and run the tool again in a vm

**Comment by ArchLeaders** [comment]
Try opening the find/replace menu using `Ctrl+F` instead of `Edit>Find`

**Comment by crustySenpai** [comment]
ctrl+f would only open the search function (which works perfectly fine for searching stuff) but i wanna replace words so it would be ctrl+h which still doesn't make it work

currently i'm just using notepad++ to replace things quick as workarround

**Comment by AsteroidPizza39** [comment]
@ArchLeaders would this have been fixed by the latest update?

**Comment by ArchLeaders** [comment]
I never had the issue on my end, so I can't really say. Worth a shot though.

**Comment by Melechtna** [comment]
Might help if you stopped hiding essential files in Discord.
[HashTable.zip](https://github.com/NX-Editor/NxEditor/files/11741294/HashTable.zip)

**Comment by ArchLeaders** [comment]
> Might help if you stopped hiding essential files in Discord.
> [HashTable.zip](https://github.com/NX-Editor/NxEditor/files/11741294/HashTable.zip)

These are not essential files, it is a configuration file for Tears of the Kingdom specifically. Furthermore, they are not in any way relevant to this issue, so please stop posting this on issues.

**Comment by Melechtna** [comment]
> > Might help if you stopped hiding essential files in Discord.
> > [HashTable.zip](https://github.com/NX-Editor/NxEditor/files/11741294/HashTable.zip)
> 
> These are not essential files, it is a configuration file for Tears of the Kingdom specifically. Furthermore, they are not in any way relevant to this issue, so please stop posting this on issues.

Firstly, I've only posted it once here, secondly, I shouldn't have had to spend 4 days trying to get the restbl editor to work only to find out you buried a VERY MUCH essential file in discord, and they don't seem to specify what they're trying to edit, but it SOUNDS like it could be related to the restbl, as this is the only file I know of that shows nothing without it, especially with the find and replace.

**Comment by ArchLeaders** [comment]
> > > Might help if you stopped hiding essential files in Discord.
> > > [HashTable.zip](https://github.com/NX-Editor/NxEditor/files/11741294/HashTable.zip)
> > 
> > 
> > These are not essential files, it is a configuration file for Tears of the Kingdom specifically. Furthermore, they are not in any way relevant to this issue, so please stop posting this on issues.
> 
> Firstly, I've only posted it once here, secondly, I shouldn't have had to spend 4 days trying to get the restbl editor to work only to find out you buried a VERY MUCH essential file in discord, and they don't seem to specify what they're trying to edit, but it SOUNDS like it could be related to the restbl, as this is the only file I know of that shows nothing without it, especially with the find and replace.

The video posted in the first comment shows him using the byml editor, and if you read and understood the issue you would know that the issue is a matter of the reactive commands from AvaloniaEdit not working, rather than a config file not being present.

Also I should clarify to you and anyone else who stumbles upon this issue, that the files posted above are not essential to the usage of the restbl editor. The file contains a list of strings from *Tears of the Kingdom* that are ***only*** used in the *Tears of the Kingdom* `rsizetable` file. Hence why, I posted the file in the *Tears of the Kingdom* discord server, not in this repository for a general Nintendo file editor.

@Melechtna if you would like to further discuss this decision you may contact me on Discord `@ArchLeaders#0903`.

I would also like to apologize for my rather uninviting response, I've had a few too many complaints about the decision so I was rather on edge about it. I'm open to discussing this further on Discord if you want, but I'm afraid this issue thread really isn't the place.

**Comment by Melechtna** [comment]
> > > > Might help if you stopped hiding essential files in Discord.
> > > > [HashTable.zip](https://github.com/NX-Editor/NxEditor/files/11741294/HashTable.zip)
> > > 
> > > 
> > > These are not essential files, it is a configuration file for Tears of the Kingdom specifically. Furthermore, they are not in any way relevant to this issue, so please stop posting this on issues.
> > 
> > 
> > Firstly, I've only posted it once here, secondly, I shouldn't have had to spend 4 days trying to get the restbl editor to work only to find out you buried a VERY MUCH essential file in discord, and they don't seem to specify what they're trying to edit, but it SOUNDS like it could be related to the restbl, as this is the only file I know of that shows nothing without it, especially with the find and replace.
> 
> The video posted in the first comment shows him using the byml editor. The issue is a matter of the reactive commands from AvaloniaEdit not working, rather than a config file not being present.
> 
> Also I should clarify to you and anyone else who stumbles upon this issue, that the files posted above are not essential to the usage of the restbl editor. The file contains a list of strings from _Tears of the Kingdom_ that are _**only**_ used in the _Tears of the Kingdom_ `rsizetable` file. Hence why, I posted the file in the _Tears of the Kingdom_ discord server, not in this repository for a general Nintendo file editor.
> 
> @Melechtna if you would like to further discuss this decision you may contact me on Discord `@ArchLeaders#0903`.
> 
> I would also like to apologize for my rather uninviting response, I've had a few too many complaints about the decision so I was rather on edge about it. I'm open to discussing this further on Discord if you want, but I'm afraid this issue thread really isn't the place.

See, that's my problem though, I'm not using a spyware messaging application to go collect files that should either be included, or available without the need of a messenger. I take the same issue with a VAST number of other projects, it's purely exclusionary and forces applications on others that they may have multiple reasons to not use them or want them. But now I'm getting off topic, but I'm also not going to your or anyone elses Discord, even if reluctantly as I do whatever I can to avoid it for the data stealing piece of adware it is.

**Comment by ArchLeaders** [comment]
> See, that's my problem though, I'm not using a spyware messaging application to go collect files that should either be included, or available without the need of a messenger. I take the same issue with a VAST number of other projects, it's purely exclusionary and forces applications on others that they may have multiple reasons to not use them or want them. But now I'm getting off topic, but I'm also not going to your or anyone elses Discord, even if reluctantly as I do whatever I can to avoid it for the data stealing piece of adware it is.
> 
> Edit: I will however thank you for trying to be less combative, as I do appreciate at least that, even if we fundamentally disagree elsewhere.

Ah yes, I can agree with you on not wanting to *require* a third party app for a QoL feature that by no means needs it.

I guess in all this I forgot to mention that the post on Discord was purely for ease, and a temporary solution while I rework the repository API to have more verbose support for games and files. In future the string table on Discord will be provided in the official TotkPlugin (https://github.com/NX-Editor/NxEditor.TotkPlugin).

I hope that clears things up, sorry for the confusion there.

**Comment by AsteroidPizza39** [comment]
@ArchLeaders Since the RSTB changes for each game version, and maybe someone is editing a pre-existing mod and needs to be able to search for the custom entries quickly, will there be a tool to generate the hashes using our own dump of the game?
